// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240118210547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("API.Entities.Grade", b =>
                {
                    b.Property<int>("IdGrad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeGrad")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdGrad");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("API.Entities.GradeMembrii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataObtinerii")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdGrad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembruId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdGrad");

                    b.HasIndex("MembruId");

                    b.ToTable("GradeMembrii");
                });

            modelBuilder.Entity("API.Entities.Membru", b =>
                {
                    b.Property<int>("MembruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivInactiv")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gen")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("NrLegitimatie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipMembru")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MembruId");

                    b.ToTable("Membrii");
                });

            modelBuilder.Entity("API.Entities.GradeMembrii", b =>
                {
                    b.HasOne("API.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("IdGrad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Membru", "Membru")
                        .WithMany()
                        .HasForeignKey("MembruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Membru");
                });
#pragma warning restore 612, 618
        }
    }
}
