version: '3.8'
services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5254:5254"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Sa123456$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
